In [4]:

import numpy as np


In [16]:
#Example 1
arr=np.random.randint(1,20,size=(3,3))
arr

array([[13,  4,  9],
       [18,  7,  2],
       [18,  7,  7]], dtype=int32)

In [ ]:
#Example 2
arr=np.random.random_integers(1,100,size=(5,5))
print(f"the element of arr{arr}")
max_arr=np.max(arr,axis=0)
print (f"the max value of row {max_arr}")
min_arr=np.min(arr,axis=0)
print (f"the min value of row {min_arr}")


the element of arr[[21 35 11 71 92]
 [69 10 36  7 87]
 [12 72 93 99 91]
 [80 71  4  3 42]
 [21 32 30 35 83]]
the max value of row [80 72 93 99 92]
the min value of row [12 10  4  3 42]


C:\Users\SHREEN\AppData\Local\Temp\ipykernel_8328\112394885.py:2: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  arr=np.random.random_integers(1,100,size=(5,5))


In [40]:
#Example 3
arr=np.random.rand(10)
sorted_arr=np.sort(arr)
sorted_arr

array([0.07294669, 0.32088549, 0.38486292, 0.38538577, 0.42424429,
       0.43525121, 0.47602805, 0.58759275, 0.89207518, 0.89885548])

In [45]:
#Example 4
arr=np.array(([1,2,3,4,56,4],[2,2,5,7,8,4],[3,9,7,5,4,3]))
uniqu_arr,counts=np.unique(arr,return_counts=True)
frequency=uniqu_arr[np.argmax(counts)]
frequency

np.int64(4)

In [47]:
#Example 5
arr=np.array([[1,2,3,4],[5,6,7,8],[9,12,11,13]])
arr[arr%2==0]=0
arr

array([[ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11, 13]])

In [49]:
#Example 6
arr=np.array([2,3,4,5,6,7,8,9])
squar=arr**2
squar

array([ 4,  9, 16, 25, 36, 49, 64, 81])

In [57]:
#Example 7
arr=np.random.random_integers(1,50,size=(3,3))
print(f"{arr}")
mean_arr=np.mean(arr)
print(f"the value of mean={mean_arr}")
subtract_mean=arr-mean_arr
subtract_mean

[[29 25 22]
 [50 23 29]
 [46 20 17]]
the value of mean=29.0


C:\Users\SHREEN\AppData\Local\Temp\ipykernel_8328\4139855147.py:2: DeprecationWarning: This function is deprecated. Please call randint(1, 50 + 1) instead
  arr=np.random.random_integers(1,50,size=(3,3))


array([[  0.,  -4.,  -7.],
       [ 21.,  -6.,   0.],
       [ 17.,  -9., -12.]])

In [65]:
#Example 8
line_space=np.linspace(1,40,20)
print(f"{line_space}")


[ 1.          3.05263158  5.10526316  7.15789474  9.21052632 11.26315789
 13.31578947 15.36842105 17.42105263 19.47368421 21.52631579 23.57894737
 25.63157895 27.68421053 29.73684211 31.78947368 33.84210526 35.89473684
 37.94736842 40.        ]


In [67]:
#another solution
odd_uum=np.arange(1,40,2)
print(f"{odd_uum}")


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


In [9]:
#Example 9
arr=np.random.random_integers(1,50,size=(5,5))
print(f"{arr}")
sort_arr=np.sort(arr,axis=0)
max_element=sort_arr[-2,:]
print (f"the max value={max_element}")


[[33 33 48 22 13]
 [42 29 11  6 43]
 [18 50 47 12 19]
 [46 30 13 35 17]
 [16 24 39 47 45]]
the max value=[42 33 47 35 43]


C:\Users\SHREEN\AppData\Local\Temp\ipykernel_14840\3878838087.py:2: DeprecationWarning: This function is deprecated. Please call randint(1, 50 + 1) instead
  arr=np.random.random_integers(1,50,size=(5,5))


In [11]:
#Example 10
arr=np.random.random_integers(1,50,size=(4,4))
print(f"{arr}")
sum_row=arr.sum(axis=1)
print(f"sum each row ={sum_row}")

[[47 19 23 45]
 [13 43 47 40]
 [10 11  4 25]
 [ 9  8 46 41]]
sum each row =[134 143  50 104]


C:\Users\SHREEN\AppData\Local\Temp\ipykernel_14840\845987436.py:2: DeprecationWarning: This function is deprecated. Please call randint(1, 50 + 1) instead
  arr=np.random.random_integers(1,50,size=(4,4))
